<?php

$lang = array(

	'other' => 'Other', //其他
	'app_connent_ok' => 'Successful communication', //通信成功 
	'app_connent_false' => 'Communication failed', //通信失敗
	'note_deleteuser' => 'Delete users', //刪除用戶
	'note_renameuser' => 'Rename user', //重命名用戶
	'note_deletefriend' => 'Delete friend', //刪除好友
	'note_gettag' => 'Get TAG', //獲取TAG
	'note_getcreditsettings' => 'Get app credit settings', //獲取應用積分設置
	'note_updatecreditsettings' => 'Update app credit settings', //更新應用積分設置
	'note_updateclient' => 'Update app cache', //更新應用緩存
	'note_updatepw' => 'Update user password', //更新用戶密碼
	'note_updatebadwords' => 'Update term filter list', //更新詞語過濾列表
	'note_updatehosts' => 'Update the domain name resolution list', //更新域名解析列表
	'note_updateapps' => 'Update application list', //更新應用列表
	'note_updatetagtemplate' => 'Update label template settings', //更新標籤模板設置
	'note_list' => 'Notification list', //通知列表
	'note_test' => 'Test', //測試
	'note_delete' => 'Delete notification', //刪除通知
	'note_succeed' => 'Notification success', //通知成功 
	'note_na' => 'Not notified', //未通知
	'note_false' => 'Notification failed', //通知失敗
	'note_times' => 'Second-rate', //次
	'pm_from' => 'From', //來自
	'pm_to' => 'Send to', //發送到
	'pm_system' => 'System information', //系統消息
	'pm_date' => 'Time', //時間
	'pm_daterange_1' => 'Today', //今天
	'pm_daterange_2' => 'Yesterday', //昨天
	'pm_daterange_3' => 'The day before yesterday', //前天
	'pm_daterange_4' => 'Last week', //上周
	'pm_daterange_5' => 'Earlier', //更早
	'pm_notitle' => '[Untitled]', //[無標題]
	'user_add' => 'Add user', //添加用戶
	'user_delete' => 'Delete users', //刪除用戶
	'login' => 'Log in', //登錄
	'logout' => 'Quit', //退出
	'app_add' => 'Add new app', //添加新應用
	'app_delete' => 'Delete app', //刪除應用
	'app_edit' => 'Edit application', //編輯應用
	'setting_update' => 'Update basic settings', //更新基本設置
	'setting_register_update' => 'Update registration settings', //更新註冊設置
	'pm_send' => 'Send a public message', //發送公共消息
	'pm_delete' => 'Delete public message', //刪除公共消息
	'pm_clear' => 'Clean up short messages', //清理短消息
	'badword_add' => 'Add word filter', //添加詞語過濾
	'badword_delete' => 'Remove word filter', //刪除詞語過濾
	'admin_add' => 'Add administrator', //添加管理員
	'admin_pw_edit' => 'Change founder password', //修改創始人密碼
	'admin_priv_edit' => 'Modify administrator privileges', //修改管理員權限
	'domain_add' => 'Add domain name resolution', //添加域名解析
	'domain_delete' => 'Delete domain name resolution', //刪除域名解析
	'credit_addexchange' => 'Update point redemption plan', //更新積分兌換方案
	'credit_deleteexchange' => 'Delete point redemption plan', //刪除積分兌換方案
	'credit_sync' => 'Sync applied credit settings', //同步應用的積分設置
	'db_export' => 'Backup data', //備份數據
	'db_import' => 'Data recovery', //恢複數據
	'db_delete' => 'Delete data', //刪除數據
	'note_send' => 'Reissue notice', //補發通知
	'dumpfile_exists' => 'Backup exists', //備份存在
	'dumpfile_not_exists' => 'Backup does not exist', //備份不存在
);